
-- Seed Feature Flags
INSERT INTO feature_flags (flag_key, display_name, description, category, is_enabled, phase) VALUES
-- Modules
('module.catalog', 'Product Catalog', 'Browse, search, and filter all products', 'module', true, '6'),
('module.inventory', 'Inventory Counting', 'Start and execute inventory count sessions', 'module', true, '8'),
('module.stock', 'Current Stock', 'View current stock levels and values', 'module', true, '8'),
('module.sessions', 'Session Management', 'View and manage inventory sessions', 'module', true, '8'),
('module.history', 'Inventory History', 'Audit log of all stock movements', 'module', true, '8'),
('module.reports', 'Reports & Analytics', 'Dashboards, charts, and data exports', 'module', false, '11'),
('module.users', 'User Management', 'Create, edit, assign roles to users', 'module', true, '3'),
('module.settings', 'Settings', 'All configuration pages', 'module', true, '4'),
('module.super_admin', 'Super Admin Panel', 'Platform-level management', 'module', true, NULL),
('module.notifications', 'Notifications', 'In-app notification center', 'module', false, '13'),
('module.receiving', 'Receiving / Deliveries', 'Log incoming deliveries', 'module', false, 'future'),
('module.waste', 'Waste / Breakage', 'Log product waste and breakage', 'module', false, 'future'),
('module.orders', 'Order Requests', 'Create and send purchase orders', 'module', false, 'future'),

-- Features (Inventory)
('feat.ai_recognition', 'AI Image Recognition', 'Camera-based product identification', 'feature', false, '9'),
('feat.barcode_scanning', 'Barcode Scanning', 'Camera barcode scanning during counting', 'feature', true, '7'),
('feat.manual_search', 'Manual Product Search', 'Text search during counting', 'feature', true, '6'),
('feat.collaborative_counting', 'Collaborative Counting', 'Multiple users count in same session', 'feature', true, '8'),
('feat.session_approval', 'Session Approval Flow', 'Require admin approval before completion', 'feature', true, '8'),
('feat.syrve_sync', 'Syrve Product Sync', 'Sync products and categories from Syrve', 'feature', true, '5'),
('feat.syrve_inventory_commit', 'Syrve Inventory Commit', 'Send completed counts to Syrve', 'feature', false, '10'),
('feat.auto_syrve_sync', 'Auto Syrve Sync', 'Scheduled automatic product sync', 'feature', false, '5'),
('feat.export_csv', 'CSV Export', 'Export data as CSV files', 'feature', false, '11'),
('feat.export_pdf', 'PDF Export', 'Export reports as PDF documents', 'feature', false, '11'),
('feat.variance_alerts', 'Variance Alerts', 'Notifications on high variances', 'feature', false, '13'),
('feat.low_stock_alerts', 'Low Stock Alerts', 'Notifications when stock drops below par', 'feature', false, '13'),
('feat.stock_value_display', 'Stock Value Display', 'Show monetary value of stock', 'feature', true, '8'),
('feat.session_expiry', 'Session Auto-Expiry', 'Auto-cancel stale sessions', 'feature', false, '8'),
('feat.glass_counting', 'Glass Dimension Counting', 'Count partial bottles using glass sizes', 'feature', true, '8'),
('feat.visual_estimate', 'Visual Volume Estimate', 'Slider-based partial bottle estimation', 'feature', false, '12'),
('feat.offline_mode', 'Offline Mode', 'IndexedDB caching for offline counting', 'feature', false, 'future'),
('feat.custom_ai_key', 'Custom AI API Key', 'Allow admin to use their own OpenAI key', 'feature', true, '9'),
('feat.multi_location', 'Multi-Location Support', 'Track inventory across multiple locations', 'feature', true, '8'),
('feat.category_filter_tree', 'Category Filter Tree', 'Hierarchical category filter in catalog', 'feature', true, '6'),
('feat.product_images', 'Product Images', 'Display and manage product images', 'feature', false, '12'),
('feat.realtime_counting', 'Realtime Session Updates', 'Live updates during collaborative counting', 'feature', false, '13'),
('feat.session_timer', 'Session Timer', 'Show live duration during counting', 'feature', false, '12'),
('feat.undo_last_count', 'Undo Last Count', 'Undo the most recent scan/count entry', 'feature', false, '12'),
('feat.receiving_from_syrve', 'Receiving from Syrve', 'Import delivery documents from Syrve', 'feature', false, 'future'),
('feat.order_to_supplier', 'Order to Supplier', 'Generate purchase orders based on stock', 'feature', false, 'future'),
('feat.search_v2', 'Search V2', 'Improved product search algorithm', 'experiment', false, NULL),
('feat.new_quantity_popup', 'New Quantity Popup', 'Redesigned quantity entry UI', 'experiment', false, NULL),
('feat.dashboard_v2', 'Dashboard V2', 'Redesigned dashboard layout', 'experiment', false, NULL),
('feat.simplified_counting', 'Simplified Counting', 'Minimal counting UI for speed', 'experiment', false, NULL),

-- Integrations
('int.syrve', 'Syrve Integration', 'Enable all Syrve connectivity', 'integration', true, '4'),
('int.openai', 'OpenAI Integration', 'Enable OpenAI Vision API access', 'integration', false, '9'),
('int.push_notifications', 'Push Notifications', 'Enable browser/mobile push', 'integration', false, 'future'),
('int.email_notifications', 'Email Notifications', 'Enable email alerts', 'integration', false, 'future'),
('int.telegram_bot', 'Telegram Bot', 'Send notifications via Telegram', 'integration', false, 'future'),
('int.webhook_outbound', 'Outbound Webhooks', 'Trigger external webhooks on events', 'integration', false, 'future'),

-- UI
('ui.dark_mode', 'Dark Mode', 'Enable dark theme option', 'ui', true, NULL),
('ui.dark_mode_toggle', 'Dark Mode Toggle', 'Show theme switcher in header', 'ui', true, NULL),
('ui.logo_in_header', 'Logo in Header', 'Show business logo in app header', 'ui', true, '8'),
('ui.business_name_in_header', 'Business Name in Header', 'Show business name next to logo', 'ui', true, '8'),
('ui.category_tabs', 'Category Tabs', 'Tab-style category filter on catalog', 'ui', true, '6'),
('ui.product_grid_view', 'Product Grid View', 'Card grid layout for catalog', 'ui', false, '12'),
('ui.dashboard_charts', 'Dashboard Charts', 'Show charts on dashboard', 'ui', false, '11'),
('ui.session_category_breakdown', 'Session Category Breakdown', 'Pie chart in session summary', 'ui', false, '12'),
('ui.sync_status_badge', 'Syrve Sync Status Badge', 'Show sync indicator in header', 'ui', true, '5'),
('ui.user_avatars', 'User Avatars', 'Display user profile pictures', 'ui', false, '12'),
('ui.animated_transitions', 'Page Animations', 'Smooth page transition animations', 'ui', false, '14'),
('ui.language_switcher', 'Language Switcher', 'Show language selector in header/profile', 'ui', false, 'future'),
('ui.currency_symbol', 'Currency Symbol Display', 'Show currency symbols', 'ui', true, NULL),
('ui.compact_tables', 'Compact Table View', 'Denser table rows for more data', 'ui', false, '12'),
('ui.quick_spot_check_button', 'Quick Spot Check', 'One-tap spot check button on dashboard', 'ui', false, '12')

ON CONFLICT (flag_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  phase = EXCLUDED.phase;
